server:
  port: 9000

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: courseService
          uri: http://localhost:8081
          predicates:
            - Path=/api/queue/**
            - Path=/api/course/**
        - id: userService
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
##          filters:
##            - AddResponseHeader=Access-Control-Allow-Origin, *
##            - RewritePath=/http://localhost:8080/(?<segment>.*), /$\{segment}
#      globalcors:
#        add-to-simple-url-handler-mapping: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


